### ISSUE TITLE
Adventurers are unable to fund an expedition

### ISSUE THREAD

**Issue by Rodna1S** [JediNick/Valyrian_Steel#2]
Hi, unsure if this is a bug or if it's intended to work this way but I recently noticed that when playing as an adventurer you lose access to the fund an expedition decision. After looking into it, I found that both the fund_expedition_decision (Line 15) and fund_expedition.0001 (lines 262, 290 and 317) have is_landed checks. Potentially changing these to use is_ruler instead could also allow adventurers to use the decision.

**Comment by JediNick** [comment]
> Hi, unsure if this is a bug or if it's intended to work this way but I recently noticed that when playing as an adventurer you lose access to the fund an expedition decision. After looking into it, I found that both the fund_expedition_decision (Line 15) and fund_expedition.0001 (lines 262, 290 and 317) have is_landed checks. Potentially changing these to use is_ruler instead could also allow adventurers to use the decision.

It's not necessarily a bug, but I have intentionally avoided this check because the mod and event chain are localized from the perspective of a landed ruler/lord. (Ie thronerooms, titled localization, etc...)

I need to rethink about what localization is displayed for adventures before making that change.
